# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - airflow_pipeline/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  RESOURCE_GROUP: testyml_group
  WEBAPP_NAME: testyml
  APP_SERVICE_PLAN:  ASP-testdockergroup-965b

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - checkout: self

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Development Subscription (d8501f72-cc6e-4c07-9f8c-b8523c3b63ec)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Deploying to Azure Web App..."
                
                # Create the web app if it does not exist
                az webapp create --resource-group $(RESOURCE_GROUP) --plan $(APP_SERVICE_PLAN) --name $(WEBAPP_NAME) --multicontainer-config-file airflow_pipeline/docker-compose.yml || true
                
                # Configure the web app to use Docker Compose
                az webapp config container set --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME) --multicontainer-config-type compose --multicontainer-config-file airflow_pipeline/docker-compose.yml
                
                # Restart the web app to apply changes
                az webapp restart --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME)
            displayName: 'Deploy to Azure Web App'
            