pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dags/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  RESOURCE_GROUP: testyml_group
  WEBAPP_NAME: testyml
  APP_SERVICE_PLAN: ASP-testdockergroup-965b
  COMPOSE_FILE_PATH: 'docker-compose.yml'

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - checkout: self

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Development Subscription (d8501f72-cc6e-4c07-9f8c-b8523c3b63ec)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Deploying to Azure Web App using Docker Compose..."

                # Ensure the web app exists
                az webapp create --resource-group $(RESOURCE_GROUP) --plan $(APP_SERVICE_PLAN) --name $(WEBAPP_NAME) || true
                
                # Enable app service storage
                az webapp config appsettings set --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME) --settings WEBSITES_ENABLE_APP_SERVICE_STORAGE=TRUE

                # Configure the web app to use Docker Compose from Docker Hub (public repository)
                az webapp config container set --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME) --multicontainer-config-type compose --multicontainer-config-file $(COMPOSE_FILE_PATH)
                
                # Restart the web app to apply changes
                az webapp restart --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME)
            displayName: 'Deploy to Azure Web App using Docker Compose'
