# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: none

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  RESOURCE_GROUP: test-1
  WEBAPP_NAME: testp
  COMPOSE_FILE_PATH: 'docker-compose.yml'

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - checkout: self

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Development Subscription (d8501f72-cc6e-4c07-9f8c-b8523c3b63ec)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Deploying to Azure Web App using Docker Compose..."

                # Ensure the web app exists
                az webapp config appsettings set --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME) --settings WEBSITES_ENABLE_APP_SERVICE_STORAGE=TRUE

                # Configure the web app to use Docker Compose from Docker Hub (public repository)
                az webapp config container set --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME) --multicontainer-config-type compose --multicontainer-config-file $(COMPOSE_FILE_PATH)

                # Restart the web app to apply changes
                az webapp restart --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME)

                echo "Transferring the dags directory to /home/dags on the web app..."
                
                # Create a zip file of the dags directory
                zip -r dags.zip dags
                
                # Use Azure CLI to upload the zip file to the web app's /home directory
                az webapp deploy --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME) --src-path dags.zip --type zip --async

                # SSH into the web app and move the dags directory directly to /home/dags
                az webapp ssh --resource-group $(RESOURCE_GROUP) --name $(WEBAPP_NAME) --command "
                unzip /home/site/wwwroot/dags.zip -d /home/ &&
                mv /home/dags /home/ &&
                rm -rf /home/site/wwwroot/dags.zip"

                echo "Dags directory successfully transferred to /home/dags."
            displayName: 'Deploy to Azure Web App using Docker Compose'
