# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '641a5b00-c982-46c8-ac54-d80edccda068'

  # Web app name
  webAppName: 'devops-airflowpipeline-app'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  environmentName: 'devops-airflowpipeline-app'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.11
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Publish artifact'
      artifact: drop

- stage: DeployPythonApp
  displayName: 'Deploy Python Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Artifacts'

    - script: ls -la $(Pipeline.Workspace)/drop/
      displayName: 'List files in drop folder'

    - script: |
        echo "Cleaning up previous deployments"
        curl -X DELETE -u $(azureServiceConnectionId):$(servicePrincipalKey) https://$(webAppName).scm.azurewebsites.net/api/vfs/site/wwwroot/
      displayName: 'Clean up previous deployments'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - task: AzureWebApp@1
      displayName: 'Deploy Azure Web App : $(webAppName)'
      inputs:
        azureSubscription: $(azureServiceConnectionId)
        appName: $(webAppName)
        package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
        deploymentMethod: 'zipDeploy'
        takeAppOfflineFlag: true
        enableXmlTransform: false
        enableCustomDeployment: true
        verbose: true

- stage: DeployDocker
  displayName: 'Docker Deploy'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Artifacts'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnectionId)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Deploying docker-compose.yml to Azure Web App using Azure CLI"
          az webapp config container set --name $(webAppName) \
            --resource-group $(environmentName) \
            --multicontainer-config-type compose \
            --multicontainer-config-file $(Pipeline.Workspace)/drop/$(Build.BuildId)/docker-compose.yml

          echo "Restarting Azure Web App to apply changes"
          az webapp restart --name $(webAppName) --resource-group $(environmentName)
      displayName: 'Deploy Docker Compose to Azure Web App'

