services:
  airflow-webserver:
    image: apache/airflow:2.9.3
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://yuoiyqabqs:KhtjzbA4aw$$xN43O@airflow-app.postgres.database.azure.com:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__BASE_URL=http://testp-fjajgnfygchaaef7.eastus-01.azurewebsites.net
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=60
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
      - AIRFLOW__WEBSERVER__SECRET_KEY=HdRmUIde3UqviEYoXUm66rMO
    volumes:
      - ${WEBAPP_STORAGE_HOME}/dags:/opt/airflow/dags
      - ${WEBAPP_STORAGE_HOME}/logs:/opt/airflow/logs
      - ${WEBAPP_STORAGE_HOME}/dags/requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command:
      - bash
      - -c
      - |
        echo "Starting Airflow Webserver setup..."
        airflow db init
        echo "Database initialized."
        airflow users create -r Admin -u admin -e admin@example.com -f Admin -l User -p admin --if-not-exists
        echo "Admin user created."
        echo "Starting Airflow Webserver..."
        airflow webserver
  airflow-scheduler:
    image: apache/airflow:2.9.3
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://yuoiyqabqs:KhtjzbA4aw$$xN43O@airflow-app.postgres.database.azure.com:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__BASE_URL=http://testp-fjajgnfygchaaef7.eastus-01.azurewebsites.net
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=60
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
      - AIRFLOW__WEBSERVER__SECRET_KEY=HdRmUIde3UqviEYoXUm66rMO
    volumes:
      - ./dags:/opt/airflow/dags
    command:
      - bash
      - -c
      - |
        echo "Waiting for webserver to be ready..."
        sleep 60
        echo "Starting Airflow Scheduler..."
        airflow scheduler
    restart: always
    depends_on:
      - airflow-webserver

