services:
  airflow-webserver:
    image: apache/airflow:2.9.3
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__BASE_URL=https://textyml-c4egbdd5c4d4aegs.eastus-01.azurewebsites.net
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    ports:
      - "8080:8080"
    command: 
      - bash
      - -c
      - |
        airflow db init &&
        if ! airflow users list | grep -q admin; then
          airflow users create -r Admin -u admin -e admin@example.com -f Admin -l User -p admin;
        fi &&
        airflow webserver
    restart: always
