services:
  airflow-webserver:
    image: apache/airflow:2.9.3
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://yuoiyqabqs:KhtjzbA4aw$$xN43O@airflow-app.postgres.database.azure.com:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__BASE_URL=https://testp-fjajgnfygchaaef7.eastus-01.azurewebsites.net
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=60
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
      - AZURE_FUNCTIONS_URL = https://manoj-azure-functions-weaviate.azurewebsites.net/api/weaviate_storage_trigger?code=kROZ6bIGyTQCLHhk3acASnzp3z4tXFw5N17224kkMuFZAzFuXD1bLQ==
    ports:
      - "8080:8080"
    command:
      - bash
      - -c
      - |
        echo "Starting Airflow Webserver setup..."
        airflow db init
        echo "Database initialized."
        airflow users create -r Admin -u admin -e admin@example.com -f Admin -l User -p admin --if-not-exists
        echo "Admin user created."
        echo "Starting Airflow Webserver..."
        airflow webserver
  airflow-scheduler:
    image: apache/airflow:2.9.3
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://yuoiyqabqs:KhtjzbA4aw$$xN43O@airflow-app.postgres.database.azure.com:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__BASE_URL=https://testp-fjajgnfygchaaef7.eastus-01.azurewebsites.net
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=60
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
      - AZURE_FUNCTIONS_URL = https://manoj-azure-functions-weaviate.azurewebsites.net/api/weaviate_storage_trigger?code=kROZ6bIGyTQCLHhk3acASnzp3z4tXFw5N17224kkMuFZAzFuXD1bLQ==
    command:
      - bash
      - -c
      - |
        echo "Waiting for webserver to be ready..."
        sleep 60
        echo "Starting Airflow Scheduler..."
        airflow scheduler
    restart: always
    depends_on:
      - airflow-webserver

