
services:
  airflow-webserver:
    image: apache/airflow:2.9.3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://yuoiyqabqs:KhtjzbA4aw$xN43O@airflow-app.postgres.database.azure.com:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__BASE_URL=https://airflow-docker-compose-v1-fga9gahehfbpaca0.southindia-01.azurewebsites.net
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admins
      - _AIRFLOW_WWW_USER_PASSWORD=admins
      - AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG
      - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=60
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
    volumes:
      - /dags:/opt/airflow/dags
      - /dags/trigger_azure_function_async.py:/opt/airflow/dags/trigger_azure_function_async.py
      - /dags/requirements.txt:/requirements.txt
    ports:
      - "8080:8181"
    command: 
      - bash
      - -c
      - |
        echo "Starting Airflow Webserver setup..."
        pip install -r /requirements.txt
        echo "Requirements installed."
        airflow db init
        echo "Database initialized."
        airflow users create -r Admin -u admin -e admin@example.com -f Admin -l User -p admin --if-not-exists
        echo "Admin user created."
        echo "Starting Airflow Webserver..."
        airflow webserver
    # command: supervisord
  
  airflow-scheduler:
    image: apache/airflow:2.9.3
    environment:
      - VARIABLE=${xN43O}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://yuoiyqabqs:KhtjzbA4aw$xN43O@airflow-app.postgres.database.azure.com:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__BASE_URL=https://airflow-docker-compose-v1-fga9gahehfbpaca0.southindia-01.azurewebsites.net
      - AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG
      - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=60
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
    volumes:
      - /dags:/opt/airflow/dags
    command: 
      - bash
      - -c
      - |
        echo "Waiting for webserver to be ready..."
        sleep 60
        echo "Starting Airflow Scheduler..."
        airflow scheduler
    # command: supervisord
    
    restart: always
    depends_on:
      - airflow-webserver
